### ISSUE TITLE
Injecting payload error

### ISSUE THREAD

**Issue by CeemoTec** [suraj-root/spade#2]
Hi Suraj, testing out the script and were getting the following error!

[*] Injecting payload...
mkdir: cannot create directory ‘slimstream/smali/com/metasploit’: No such file or directory
mkdir: cannot create directory ‘slimstream/smali/com/metasploit/stage’: No such file or directory
cp: target 'slimstream/smali/com/metasploit/stage/' is not a directory
[-] [Errno 2] No such file or directory: 'slimstream/smali//Splash.smali'

can you advise?

**Comment by suraj-root** [comment]
Did the de-compilation worked perfectly? can you see a folder created with the name of the apk (i,e; slimstream)?

**Comment by yavuzgokhan** [comment]
I have same error. I crate temp.apk and temp folder.. Temp folder contains androidmanifest.xml apktool.yml and orginal rest smali folders..

**Comment by papsire** [comment]
I cant find the final apk

**Comment by hiw0rld** [comment]
I have same error  and then change another apk.  That works right
Too errors for debug
change the apktool
audit the AndroidManifest.xml
rebuild the apk
then  bingo!

**Comment by suraj-root** [comment]
Spade's development is discontinued because of its compatibility issue and its code inefficiency, a new framework will be released in the near future, make sure to check out the same module there.
