### ISSUE TITLE
File Copy Error while running the program

### ISSUE THREAD

**Issue by dineshshetty** [suraj-root/spade#4]
I tried to run the program on some file. I keep getting an error as shown below:

`[+] File /root/tools/spade/<theapknamegoeshere> OK 
cp: '/root/tools/spade/<theapknamegoeshere>' and '<theapknamegoeshere>' are the same file
[-] Couldn't make a copy of <theapknamegoeshere>`

**Comment by suraj-root** [comment]
it was a small mistake, in the latest commit i fixed it, clone the repo again and it will work

commit : https://github.com/suraj-root/spade/commit/f5c145f550a783edac0e56b6cabc1cf4935aa8f6
