### ISSUE TITLE
Some phone A/V detect the 'metasploit' strings

### ISSUE THREAD

**Issue by benichmt1** [suraj-root/spade#5]
Hi,
I was testing the project on my phone with Avast Antimalware to see if it would detect the backdoored apk. Although it complained, I was able to successfully install it.

I was working on trying to obscure the names in the new apk, especially <code>smali/com/metasploit/</code> and the like but I'm not 100% sure how the android meterpreter works.

Right now if I alter the names at the key locations the app will crash.

**Comment by suraj-root** [comment]
Yes, the AVs detect. Spade's development is discontinued because of its compatibility issue and its code inefficiency, a new framework will be released in the near future, make sure to check out the same module there, I will try adding persistence and evasion in the near future.
