### ISSUE TITLE
no output .apk file ? 

### ISSUE THREAD

**Issue by roothaxor** [suraj-root/spade#8]
I was testing this project on ubuntu 14.04 64bit
everything works fine my app name was apk.apk, when i used your scripts it told me apk saved as final-apk.apk but there is no file created.
i did'nt checked codes no idea what is going on so tell me

**Comment by suraj-root** [comment]
Spade's development is discontinued because of its compatibility issue and its code inefficiency, a new framework will be released in the near future, make sure to check out the same module there.
